export const Strings = {
  globals: {
    appName: 'REI Reserve',
  },
  connectionerror: {
    title: 'Connection Error',
    // errormessage:
    //   'Looks like you have lost your connection to the internet. Please check your settings or try again later.',
    errormessage:
      'There is an issue with connecting to the server,  please check your signal or Wi-Fi - and try again',
    errormessageone: 'No internet connection.',
  },
  commonerror: {
    title: 'Server Error',
    errormessage:
      'We have not been able to process your instruction,  please check later - and try again',
  },
  serverDownError: {
    title: 'Server Error',
    errormessage: 'Ooops! Something has gone wrong.',
    errormessage2:
      'For help and support with the application please contact our client services team',
    // errormessage3: '0800 832 832',
    // errormessage4: 'or +44 1268 443914 if you are calling from overseas',
  },
  sessionError: {
    title: 'Session Expired',
    errormessage:
      'Your session has timed out.Please log in again to continue using the app.',
  },
  common: {
    dasboard: 'Dashboard',
    investments: 'Investments',
    contributions: 'Contributions',
    history: 'History',
    activity: 'Activity',
    confirm: 'Confirm',
    hi: 'Hi',
    logIn: 'Log In',
    logIn2: 'Login',
    logIn3: 'Log in',
    registerForAccess: 'Register for access',
    notYetInvested: 'Not yet invested?',
    next: 'Next',
    confirmChanges: 'Confirm Changes',
    postcode: 'Postcode',
    country: 'Country',
    alert: 'Alert',
    ok: 'Ok',
    dateOfBirth: 'Date of birth',
    select: 'Select',
    selectCountry: 'SELECT COUNTRY',
    invalidDob: 'Invalid date of birth',
    invalideDobMsg: 'You must be at least 18 to have an account',
    close: 'Close',
    accountNumber: 'Account number',
    emailAddress: 'Email address',
    noThanks: 'No, Thanks',
    yes: 'Yes',
    no: 'No',
    outlooK: 'Outlook',
    gmail: 'Gmail',
    codeExpired: 'Code expired',
    codeExpiresIn: 'Code expires in',
    phoneNumber: 'Phone number',
    pleaseEnterSixDigitCode: 'Please enter the 6 digit code',
    resend: 'Resend',
    done: 'Done',
    forgottenPassword: 'Forgotten Password?',
    email: 'Email',
    phone: 'Phone',
    telephone: 'Telephone',
    delete: 'Delete',
    address: 'Address',
    relation: 'Relation',
    pleaseSelect: 'Please select',
    relationToYou: 'Relation to you',
    relationToYouCaps: 'RELATION TO YOU',
    info: 'INFO',
    textMessage: 'Text message',
    enablePushNotifications: 'Enable push notifications',
    noThanks2: 'No thanks',
    accounts: 'Accounts',
    search: 'Search',
    help: 'Help',
    profile: 'Profile',
    more: 'More',
    edit: 'Edit',
    faqs: 'FAQS',
    faqs1: 'FAQs',
    seeMore: 'See more',
    seeAll: 'See all',
    logout: 'Logout',
    failedToOpenUrl: 'Failed to open url.',
    urlNotAvailable: 'Url not available',
    trade: 'Trade',
    retry: 'Retry',
    buy: 'Buy',
    sell: 'Sell',
    switch: 'Switch',
    addCash: 'Add cash',
    withdraw: 'Withdraw',
    unableToFetch: 'Unable to fetch.',
    thankYou: 'Thank you',
    review: 'REVIEW',
    review1: 'Review',
    sorry: 'Sorry',
    optional: 'optional',
    guardianTitle: 'Guardian Title',
    yourTitle: 'YOUR TITLE',
    bankDetailsAdded: 'Your bank details have been added',
    bankVerificationFailedMessage:
      'Sorry We have not been able to verify your bank details.',
    downloadOfflineBankDetailForm: 'Download offline bank details form',
    emptyPlaceHolderBankAccount: '- - - - - - - -',
    emptyPlaceHolderSortCode: '- -  - -  - -',
    descOfflineAddBankDetails:
      'To add new bank details, please download the offline form, which can either be posted to us on the address below, or can be uploaded via  the document upload facility when you login through the website.',
    back: 'Back',
    iAgree: 'I agree',
    noContent: 'Content not available.',
    noRecordFound: 'No transaction records found',
    overview: 'OVERVIEW',
    buildingHouseNumber: 'Building/House number',
    notAllowed: 'Not Allowed',
    notAvailable: 'Not Available',
    thisActionNot: 'This action is not available for this plan',
    date: 'Date',
    reference: 'Reference',
    description: 'Description',
    cashIn: 'Cash in',
    cashOut: 'Cash out',
    balance: 'Balance',
    confirmPayment: 'Confirm payment',
    goToWebsite: 'Go to Website',
    pence: 'Pence',
    cancel: 'Cancel',
    fundNotFound: 'Fund not found',
    signOut: 'Sign out',
    signOutConfirmation: 'Are you sure you want to sign out?',
    invalidInput: 'Invalid input',
    serverIssueAfterPaymentMsg:
      'There is a server issue. If the amount has been debited, it will be credited back to your account within 3 to 5 business days.',
    maintenanceMsg:
      'The App is temporarily unavailable to carry out essential site maintenance.',
    maintenanceMsg2:
      'We are sorry for any inconvenience this causes you and would like to thank you for your understanding.',
    updateMsg: 'A newer version of this App is available in the ',
    updateMsg2: 'Please go to the ',
    updateMsg3: 'to download and install the latest version.',
    backToLogin: 'Back to Login?',
    backAlertMsg:
      "If you go back, you won’t be able to use biometrics. You will need to sign in with your email and password.",
    update: 'Update',
    enter: 'Enter',
    leavePage: 'Leave page',
    warning: 'WARNING',
    confirmDelete: 'CONFIRM DELETE?',
    na: 'Not Applicable',
    fileExists: 'File Exists',
    fileAlreadyExistsReplace: 'A file with this name already exists. Do you want to replace it?',
    permissionDenied: 'Permission Denied',
    storagePermissionRequired: 'Storage permission is required to download files. Please grant permission in app settings.',
    documentUrlNotAvailable: 'Document URL not available',
    error: 'Error',
    noApplicationFoundToOpenDocument: 'No application found to open this document',
    openSettings: 'Open Settings',
    noAppAssociated  : 'No app associated'
  },
  landingPage: {
    slogan: 'Secure your future',
    beforYouStart: 'Before you start',
    howToGetAccess: 'How to get access?',
    activateYourFaceId: 'Activate your Face ID',
    activateYourFaceIdDescription:
      'Login easily and securely with the biometric choice on your smartphone.',
    activateYourBiometrics: 'Activate your Biometrics',
    activateYourBiometricsDescription:
      'Login easily and securely with the biometric choice on your smartphone.',
    loginWithEmailPassword: 'Login with email & password',
  },
  registrationPage: {
    almsotThere: 'You are almost there',
    almsotThereDesc:
      'Let’s secure your application now, please select the password and biometrics',
    yourName: 'Your name',
    yourNameMsg:
      'To confirm your identity this should be exactly the same as on your ID or passport.',
    yourDob: 'Your date of birth',
    yourDobMsg:
      'Please type your date of birth below or use the date selector.',
    yourCountry: 'Your country',
    yourCountryMsg: 'Please select your country below:',
    yourPostcode: 'Your postcode',
    yourPostcodeMsg: 'Please type your postcode below:',
    yourAccountNumber: 'Your account number',
    yourAccountNumberMsg:
      'Please enter your account number, which you can find at the top of your statement.',
    yourEmailAddress: 'Your email address',
    yourEmailAddressMsg:
      'Please enter your email address so it can be verified.',
    createPassword: 'Create the password',
    pwdDesc:
      'Please choose a strong memorable password that matches the criteria below.',
    rePassword: 'Re-enter password',
    authentication: 'Authentication',
    authenticationDesc:
      "When you login, we’ll send you a code to ensure it’s you",
    authenticationDesc1: 'Where you would like to receive your code?',
    authenticationDesc2: 'Your code will be sent to you via:',
    activateBiometrics: 'Activate Biometrics',
    activateBiometricsDesc:
      'Login easily and securely with the biometric choice on your smartphone.',
    biometricConfirmTitle: 'Use Biometrics to log in?',
    biometricConfirmDesc: 'Use Biometrics to log in to your trading account',
    password: 'Password',
    typehere: 'type here',
    sms: 'SMS',
    email: 'E-mail',
    activateFaceId: 'Activate biometric login',
    loginEmail: 'Login with email & password ',
    loginEmailInstead: 'Use email & password instead',
    useBometric: 'Activate your Biometrics',
    useBometricDesc:
      'Use biometrics on your smartphone to log in to your account',
    verifyYourEmail: 'Verify your email',
    verifyEmailMsg:
      'We\'ve sent a 6-digit code to your new email address. Please enter it below to verify your email.',
    useDifferentEmail: 'Use a different email',
    useDifferentNumber: 'Use a different number',
    verifyYourNumber: 'Verify your number',
    verifyYourMobile: 'Verify your mobile',
    verifyYourMobileMsg:
      'Please enter your mobile so we send you the the verification code',
    verifyYourMobileMsg2:
      'We just sent you a verification code to your mobile, please put it here',
    securityQuestions: 'Security questions',
    securityQuestionsMsg:
      'If you have trouble signing in, answer these 3 memorable questions to verify your identity',
    selectAQuestion: 'Select a question',
    selectAQuestionMsg: 'Please select a memorable question.',
    stayUptoDate: 'Stay up to date',
    stayUptoDateDesc: 'Never miss an important updates ',
    marketingPreferences: 'Marketing preferences',
    marketingPreferencesDesc:
      "Occasionally we'll contact you about your account or with offers. How would you prefer to be contacted?",
    verifyYourMobileMsg3:
      'We\'ve sent a 6-digit code to your new mobile number. Please enter it below to verify your number.',
    invalidEMailMsg: 'Please use a valid email address',
  },
  dashboardPage: {
    openANewAccount: 'OPEN A NEW ACCOUNT',
    openANewAccount2: 'Open a new account',
    openAccountIntroText:
      "It's great to have you onboard!  Simply choose the account type you want, add a few details, pick your investments and then you're good to go.",
    welcome: 'Welcome',
    welcomeBack: 'Welcome back,',
    totalAssetValue: 'Total asset value as of',
    pound: '£',
    bannerText:
      "If you're considering making an investment into European Assets Trust, please be advised the Board has announced proposals to combine with The European Smaller Companies Trust PLC. Find out more at ",
    bannerLink: 'European Assets Trust | European Investment Equities',
    totalBalance: 'Total Balance',
    activeInvestments: 'Active Investments',
    monthlyContribution: 'Monthly Contribution',
    funds: 'Funds',
    quickActions: 'Quick Actions',
    viewAccounts: 'View Accounts',
    viewInvestments: 'View Investments',
    viewContributions: 'View Contributions',
    portfolioSummary: 'Portfolio Summary',
    balanceHistory: 'Balance History',
    yourContributions: 'Your Contributions',
    investmentSummary: 'Investment Summary',
    beneficiaries: 'Beneficiaries',
    recentHistory: 'Recent History',
    navigateToContributionsDetails: 'Navigate to contributions details',
    yourAccounts: 'YOUR ACCOUNTS',
    yourPolicies: 'YOUR POLICIES',
    estimatedBalanceAsOf: 'Total value of your account as of',
    accountsCombinedAsOf: 'Value of all accounts combined as of',
    estimatedReturns: 'Estimated returns',
    incomeStream: 'Income Stream',
    noAccountsFound: 'No accounts found',
    failedToLoadAccounts: 'Failed to load accounts',
  },
  accountsPage: {
    accountsSummary: 'Account Summary',
    cashBalance: 'Cash balance',
    accountValueAsOf: 'Total value of your account as of',
    monthlyContributions: 'Monthly Contributions',
    setUpMonthlyContribution: 'Set up a monthly contribution',
    isaAllowance: 'ISA Allowance',
    paidIn: 'Paid in',
    remaining: 'Remaining',
    yourInvestments: 'Investments',
    startInvestingToday: 'Start investing today',
    recentHistory: 'RECENT HISTORY',
    recentActivity: 'RECENT ACTIVITY',
    recentTransactions: 'RECENT TRANSACTIONS',
    pendingTransactions: 'PENDING TRANSACTIONS',
    noTransactions: 'No transactions available',
    noInvestmentsFound: 'No Investments Found',
    failedToLoadInvestmentSummary: 'Failed to load investment summary',
    noBeneficiariesFound: 'No Beneficiaries Found',
    failedToLoadBeneficiariesSummary: 'Failed to load beneficiaries summary',
    sortHoldings: 'SORT HOLDINGS',
    valueHighest: 'Value - Highest',
    valueLowest: 'Value - Lowest',
    ascending: 'Alphabet - ascending',
    descending: 'Alphabet - descending',
    openANewISA: 'Open a new ISA.',
    openANewGIA: 'Open a new GIA.',
    openANewJISA: 'Open a new JISA.',
    openANewLISA: 'Open a new LISA.',
    transactions: 'Transactions',
    transactionHistory: 'Transaction history',
    transactionDetails: 'Transaction details',
    moneyin: 'Money in',
    moneyout: 'Money out',
    feescharges: 'Fees & charges',
    last30days: 'Last 30 days',
    last3months: 'Last 3 months',
    last6months: 'Last 6 months',
    last12months: 'Last 12 months',
    searchTransactions: 'Search transactions',
    totalIncCharges: 'Total amount inc. charges',
    transactionType: 'Transaction type',
    dealDate: 'Deal date',
    price: 'Price',
    holdings: 'Holdings',
    dealID: 'Deal ID',
    marketname: 'Market name',
    settlementStatus: 'Settlement status',
    dealConsideration: 'Deal consideration',
    transactionTypeUpper: 'Transaction type',
    periodFor: 'PERIOD FOR',
    year: 'YEAR',
    withdrawal: 'Withdrawals',
    investment: 'Investments',
    all: 'All',
    regularInestment: 'Regular investments',
    paymentSettings: 'Payment settings',
    paymentDetails: 'Payment details',
    cashTransactions: 'Cash transactions',
    cashTransaction: 'Cash transaction',
    cashOverview: 'Cash overview',
    moreOptions: 'More Options',
    noPendingTransactionMsg: 'No pending transactions available',
    totalValue: 'Total Value',
    latestPrice: 'Latest Price',
    units: 'Units',
    fundSize: 'Fund size',
    priceDates: 'Price dates',
    cumulative: 'Cumulative',
    discrete: 'Discrete',
    performance: 'Performance',
    performanceDisclaimer1:
      'Values are based on the latest available closing mid-price for Investment Trusts',
    performanceDisclaimer2:
      'Past performance is not an indication of future performance.',
    performanceType: 'PERFORMANCE TYPE',
    numOfHoldings: 'Your holdings',
    currency: 'Currency',
    makeChanges: 'Make changes to your payment settings for:\n',
    BankDetails: 'BANK DETAILS',
    defaultAccount: 'Default account',
    removeAccount: 'Remove account',
    makeThisMyDefault: 'Make this my default account',
    annualFees: 'ANNUAL FEES',
    chooseHowYou: 'Choose how you pay your fees:',
    directDebit: 'Direct Debit',
    incomePreference: 'INCOME PREFERENCE',
    chooseHowYouWant: 'Choose how you want to receive income payments.',
    reinvested: 'Reinvested',
    payYourFeesBy: 'Pay your fees by - ',
    incomePreferences_: 'Income preferences - ',
    chooseHowYouWouldLike:
      'Choose how you would like dividends to be paid for ISA | 01234567',
    incomePreferences: 'INCOME PREFERENCES',
    deductFromMyShares: 'Deduct from my shares',
    reinvest: 'Reinvest',
    payToMyBank: 'Pay to my bank account',
    pleaseLogIntoTheWebsiteToOpen:
      'Please log into the Website to Open a New Account',
    noPaymentSettings:
      'There are no payment details on your account yet, please log into the website where you can update your account record, with a UK banks account',
    // diclaimerText:'If you would like to make changes to your payment settings, you can do it by logging on to the website',
    portfolioSummary: 'Portfolio Summary',
    balanceHistory: 'Balance history',
    yourContributions: 'Your contributions',
    investmentSummary: 'INVESTMENT SUMMARY',
    beneficiaries: 'BENEFICIARIES',
    beneficiaries1: 'Beneficiaries',
    employerMandatory: 'Employer Mandatory',
    employerVoluntary: 'Employer Voluntary',
    employeeVoluntary: 'Employee Voluntary',
    fundsInvested: 'Funds invested',
    noFundsInvested: 'No funds invested',
    guardian: 'Guardian',
    age: 'Age',
    contributionsSummary: 'Contributions Summary',
    employer: 'Employer',
    you: 'You',
    viewContributions: 'View contributions',
    selectAnOption: 'Select an option',
    selectPolicy: 'SELECT POLICY',
    navigateToContributionsDetails: 'Navigate to contributions details',
    mnageBeneficiaries: 'Manage\nBeneficiaries',
  },
  contributions: {
    contributions: 'Contributions',
    totalContributions: 'Total contributions',
    planChoose: 'ABC International Plan',
    recentContributions: 'RECENT CONTRIBUTIONS',
    contributionsSources: 'CONTRIBUTION SOURCES',
    totalContributionsToDate: 'Total Contributions to Date',
  },
  history: {
    history: 'History',
  },
  investmentsPage: {
    performance: 'PERFORMANCE',
    overallVsAnnualisedPerformance: 'Overall vs Annualised Performance',
    fundAllocation: 'Fund Allocation',
    noFundDetailsAvailable: 'No fund details available',
    overview: 'OVERVIEW',
    investment: 'Investment',
    units: 'No. of units',
    unitPrice: 'Unit price',
    balanceSplit: 'Balance split (%)',
    balance: 'Balance',
    priceDate: 'Price date:',
    fundAllocations: 'FUND ALLOCATIONS',
  },
  fund: {
    sinceStart: 'Since start',
    details: 'Details',
    aboutThisFund: 'About this fund',
    averageReturn: 'Average return',
    topTen: 'Top 10',
    sector: 'Sector',
    percentage: 'Percentage',
    documents: 'Documents',
    keyInvestorInformation: 'Key Investor Information(KID/KIID) ',
    fundFactSheet: 'Fund fact sheet',
    SDRCFD: 'SDR CFD',
    SDRCFDescription:
      'This product has some sustainability characteristics, which is explained in the SDR Consumer Facing Document. It does not pursue a sustainability objective and does not meet the criteria for a sustainable investment label. As such, this product does not have a UK sustainable investment label. Sustainable investment labels help investors find products that have a specific sustainability goal.',
  },
  profile: {
    updateName: 'Update name',
    updateMaritalStatus: 'Update marital status',
    updateGender: 'Update gender',
    pleaseEnterYourNumber:
      'Please enter your number so we send you the the verification code',
    thisEmailIs:
      'This email is used to login to your online account. Please enter your new email address so it can be verified.',
    pleaseTypeYourPostcode: 'Please type your postcode and house number below:',
    changePhoneNumber: 'Change phone number',
    prefDescription:
      "Occasionally we'll contact you about your account or with offers. How would you prefer to be contacted?",
    faceId: 'Face ID',
    emailPassword: 'Email & password',
    textMessage: 'Text message',
    twoFactorQuestion: 'How do you want to receive your code?',
    twoFactorDescription:
      "When you login with email and password, we will send you averification code to ensure it’s you",
    twoFactorAuth: 'TWO FACTOR AUTHENTICATION',
    loginMethod: 'LOGIN METHOD',
    addNew: 'Add new',
    communicationPreferences: 'Communication preferences',
    loginPreferences: 'Login preferences',
    updateSecurityQuestions: 'Update security questions',
    changePassword: 'Change password',
    bankDetails: 'Bank details',
    accountHolderName: 'Account holder name',
    bsb: 'BSB',
    yourDetails: 'YOUR DETAILS',
    security: 'SECURITY',
    stayingInTouch: 'STAYING IN TOUCH',
    fullName: 'Full name',
    firstName: 'First Name',
    middleName: 'Middle Name(optional)',
    lastName: 'Last Name',
    dateOfBirth: 'Date of birth',
    homeAddress: 'Home Address',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    homePhoneNumber: 'Home phone number',
    personalDetails: 'Personal details',
    manageBeneficiaries: 'Manage Beneficiaries',
    notSetYet: 'You have not set up that yet!',
    beneficiaries: 'BENEFICIARIES',
    beneficiaries1: 'Beneficiaries',
    logoutTitle: 'Logout',
    logoutMessage: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    replace: 'Replace',
    yes: 'Yes',
    sampleUserName: 'Alyson Lauryn Sutton',
    emailMeAbout: 'EMAIL ME ABOUT',
    email: 'Email',
    phone: 'Phone',
    contact: 'Contact',
    correspondence: 'Correspondence',
    benefitStatement: 'Benefit Statement',
    offersAndInformation: 'Offers and Information',
    optInGhafBenefits:
      'I opt in to be contacted by the Ghaf Benefits Group for limited and specific purposes',
    readAgreeTerms: 'I have read and agree with the ',
    termsAndConditions: 'Terms and Conditions',
    savePreferences: 'Save Preferences',
    incorrectDateOfBirth: 'INCORRECT DATE OF BIRTH?',
    nameChange: 'NAME CHANGE',
    maximumAvailable: 'Maximum available',
    incorrectNameMsg:
      'If your name is incorrect, please write to us at the address below and include a copy of your passport and driving licence:',
    incorrectDOBMsg:
      'If your date of birth is incorrect, please write to us at the address below and include a copy of your passport and driving licence:',
    removeBankConfirm: 'Are you sure you want to remove this bank account?',
    contactInformation: '',
    personalInformation: '',
    gender: 'Gender',
    maritalStatus: 'Marital status',
    idNumber: 'Member number',
    mobileNumber: 'Mobile number',
    physicalAddress: 'Residential address',
    postalAddress: 'Postal address',
    taxFileNumber: 'Tax file number (TFN)',
    atoSuperMatchConsent: 'ATO super match consent',
    notSupplied: 'Not supplied',
    supplied: 'Supplied',
    useMyPhysicalAddress:
      'Use my residential address - the content of this part will be defined',
    removeBankBtnText: 'Yes, remove bank details',
    removeBankSuccess: 'Your bank details have been removed',
    securityQuestionTitle:
      'If you have trouble signing in, answer these 3 memorable questions to verify your identity',
    securityQuestionUpdateSuccess: 'Your security questions have been updated',
    passwordUpdateSuccess: 'Your password has been updated',
    newPasswordTitle: 'Enter a new password',
    currentPassword: 'Change password',
    enterYourPassword: 'Enter your current password',
    noPersonalData: 'No personal data available',
    noBankDetails: 'No bank details available',
    goToPersonalDetails1: 'Go to ',
    goToPersonalDetails2: 'Personal Details',
    goToPersonalDetails3:
      ' to view and update your contact information.  Please note: You will continue to receive notifications on this platform. ',
    verifyOtp: 'Verify OTP',
    updateYourEmail: 'Update your email',
    updateYourAddress: 'Update your address',
    updateYourMobile: 'Update your mobile number',
    updateYourPhone: 'Update your phone',
    enterYourPhone:
      'Enter your new mobile number below. We\'ll send you a code to verify this number.',
    enterYourEmail:
      'Enter your new email address below. We\'ll send you a code to verify this email.',
    enterYourAddress: 'Enter your address',
    shortDescriptionText:
      'Short description text of this page to be defined at content review stage of the project',
    enterAddressDescription:
      'Enter your address below. If not found, you can enter it manually',
    enterOtpDescription: 'Enter the OTP sent to your device',
    startTypingAddress: 'Start typing to search for your address',
    phoneNumberPlaceholder: '78912345678',
    emailPlaceholder: 'example@gmail.com',
    mobileNumberPlaceholder: '78912345678',
    addressPlaceholder: 'Address',
    otpPlaceholder: 'Enter OTP',
    enterAddressPlaceholder: 'Enter your address',
    mobileNumberField: 'Mobile number',
    addressSearch: 'Address search',
    verify: 'Verify',
    pleaseEnterYourPhoneNumber: 'Please enter your phone number',
    pleaseEnterValidPhoneNumber: 'Please enter a valid phone number',
    pleaseEnterYourEmailAddress: 'Please enter your email address',
    pleaseEnterValidEmailAddress: 'Please enter a valid email address',
    pleaseEnterYourMobileNumber: 'Please enter your mobile number',
    pleaseEnterValidMobileNumber: 'Please enter a valid mobile number',
    pleaseEnterYourAddress: 'Please enter your address',
    pleaseEnterValidAddress: 'Please enter a valid address',
    phoneNumberUpdatedSuccess: 'Your phone number has been updated',
    emailAddressUpdatedSuccess: 'Your email has been updated',
    mobileNumberUpdatedSuccess: 'Your mobile number has been updated',
    physicalAddressUpdatedSuccess: 'Your address has been updated',
    informationUpdatedSuccess: 'Your information has been updated successfully',
    enterManually: 'Enter manually',
    loading: 'Loading...',
    pleaseEnterSixDigitCode: 'Please enter the 6 digit code',
    codeExpires: 'Code expires in 1:38',
    enterManuallyText: 'Enter manually',
    address1: 'Address 1',
    address2: 'Address 2',
    suburb: 'Suburb',
    state: 'State',
    country: 'Country',
    postcode: 'Postalcode',
    buildningName: 'Building Name',
    streetNumberAndName: 'Street Number and Name',
    parishTownCity: 'Parish/Town/City',
    emirate: 'Emirate',
    pleaseSelect: 'Please Select',
    selectedAddress: 'Selected address',
    confirmAddressChange: 'Confirm address change',
    checkDetailsCarefully:
      'Please check the details carefully before confirming',
    notSet: 'Not Set',
    totalAllocation: 'Total Allocation',
    saveChanges: 'Save Changes',
    contactDetails: 'CONTACT DETAILS',
    noBeneficiaries: 'No beneficiaries have been set',
    allocation: 'ALLOCATION',
    allocation1: 'Allocation',
    deleteBeneficiary: 'Are you sure you want to delete',
    asYourBeneficiary:
      'as your beneficiary, you will be required to update the allocation on the next screen',
    addNewBeneficiary: 'Add New Beneficiary',
    updateBeneficiary: 'Update beneficiary',
    updateBeneficiaryDescription:
      'Short description text of this page to be defined at content review stage of the project',
    updateRelation: 'Update relation to you',
    updateRelationDescription:
      'What is your relation to nominated beneficiary?',
    updateDateOfBirth: 'Update date of birth',
    updateDateOfBirthDescription:
      'Please provide the date of birth of your nominated beneficiary',
    updateAllocation: 'Update allocation',
    updateAllocationDescription:
      'Short description text of this page to be defined at content review stage of the project',
    updateGuardianDetails: 'Update Guardian Details',
    updateGuardianDetailsDescription:
      'Short description text of this page to be defined at content review stage of the project',
    accountNumber: 'Account number',
    // Info tooltips for personal details fields
    featureNotOnMobile: 'This feature is not available on mobile yet',
    infoTooltips: {
      fullName:
        'Please login to Web Portal to submit your request to update your name, along with one of the required documents',
      taxFileNumber:
        'Please login to Web Portal to submit your request to update your Tax file number, along with one of the required documents',
      atoSuperMatchConsent:
        'Please login to Web Portal to submit your request to update your ATO super match consent, along with one of the required documents',
      dateOfBirth:
        'Please login to Web Portal to submit your request to update your date of birth, along with one of the required documents',
      gender:
        'Please login to Web Portal to submit your request to update your gender, along with one of the required documents',
      maritalStatus:
        'Please login to Web Portal to submit your request to update your marital status, along with one of the required documents',
    },
  },
  beneficiaries: {
    start: 'Start',
    editAllocations: 'Edit Allocations',
    createBeneficiary: 'Create Beneficiary',
    createNew: 'Create New',
    updateAllocations: 'Update allocations',
    updateAllocationsDescription:
      'Define how much of your benefit each nominated beneficiary should receive',
    review: 'Review',
    allocationExceeds100: 'Total allocation must be 100% to save the changes',
    allocationBelow100:
      'Total allocation must be 100%, if you add more beneficiaries, you will be able to allocate diffrent % for each beneficiary',
    allocationOneZero: 'Each beneficiary requires at least 1% to be allocated',
    allocationSuccess: 'You have correctly allocated all beneficiaries',
    pleaseSelectTitle:
      'Please select the beneficiaries title to help us address them correctly',
    pleaseProvideLegalName:
      'Please provide the legal name of your nominated beneficiary',
    detailsInfoUpdateSuccess: 'You have successfully updated beneficiary info',
    updateContact: 'Update contact',
    updateContactDescription:
      'Please enter the new mobile number where we send the verification code.',
    updateEmail: 'Update email (optional)',
    updateAddress: 'Update address',
    updateAddressDescription:
      'Please check the details carefully before confirming',
    updateDetails: 'Update details',
    updateGuardianTitleDescription: 'Please select the guardian title to help us address them correctly',
    detailsContactUpdateSuccess: 'You have successfully updated beneficiary contact details',
    detailsGuardianUpdateSuccess: 'You have successfully updated guardian details',
    detailsAllocationUpdateSuccess: 'You have successfully updated the allocation',
    cancelReallocationText: "Since you haven't completed re-allocation stage, your beneficiary",
    willstay: 'will stay as it was',
    // Validation messages
    validContactNumber: 'Please use a valid contact number',
    validEmailAddress: 'Please use a valid email address',
    // Success messages
    beneficiarySetupSuccess: 'You have successfully set up the beneficiary ',
    beneficiarySetupSuccessWithGuardian:
      'You have successfully set up the beneficiary with Guardian',
    beneficiaryUpdateSuccess: 'You have successfully updated beneficiary',
    beneficiaryAllocationUpdateSuccess:
      'You have successfully updated the allocation',
    beneficiaryDeleteSuccess: 'You have successfully deleted the beneficiary',

    // Toggle labels
    beneficiaryRequiresGuardian: 'This beneficiary requires Guardian',
    useMyPhysicalAddress: 'Please use my physical address',
    // Page titles
    updateBeneficiaryTitle: 'Update beneficiary',
    // Description suffixes
    relationToYouSuffix: ' to you?',
    // Page titles
    beforeYouStart: 'Before you start',
    beneficiaryDetails: 'Beneficiary Details',
    addNewBeneficiary: 'Add new beneficiary',
    dateOfBirth: 'Date of birth',
    contactNumber: 'Contact number',
    emailAddress: 'Email address',
    beneficiaryAddress: 'Beneficiary address',
    confirmAddress: 'Confirm address',
    guardianDetails: 'Guardian Details',
    guardianTitle: 'Guardian Title',
    guardianTitle1: 'Guardian title',
    guardianName: 'Guardian Name',
    guardianContact: 'Guardian contact',
    guardianEmail: 'Guardian Email',
    guardianAddress: 'Guardian Address',
    confirmGuardianAddress: 'Confirm Guardian Address',
    guardianDateOfBirth: 'Guardian date of birth',
    relationToYou: 'Relation to you',
    allocation: 'Allocation',
    selectAllocation: 'Select allocation',
    reviewAndConfirm: 'Review and confirm',
    // Descriptions
    beforeYouStartDescription:
      'Please make sure you have all following information available before starting setting up the beneficiary.',
    beneficiaryDetailsDescription:
      'If the beneficiary has been created before, please select from the list below, otherwise create a new',
    selectBeneficiaryTitleDescription:
      'Please select the beneficiaries title to help us address them correctly',
    provideLegalNameDescription:
      'Please provide the legal name of your nominated beneficiary',
    provideDateOfBirthDescription:
      'Please provide the date of birth of your nominated beneficiary',
    providePhoneNumberDescription:
      'Please enter the phone number of your nominated beneficiary',
    provideEmailAddressDescription:
      'Please enter the email address of your nominated beneficiary',
    checkDetailsCarefullyDescription:
      'Please check the address details carefully before confirming',
    confirmAddressDetailsDescription: 'Please check the details carefully before confirming',
    confirmBeneficiaryAddressDescription:
      "Please confirm the beneficiary's address details",
    guardianDetailsDescription:
      'If you have beneficiaries created before that you would like to use as guardians, please select from the list below, otherwise you can create a new guardian',
    selectGuardianTitleDescription:
      'Please select the guardian title to help us address them correctly',
    provideGuardianNameDescription:
      'Please provide the legal name of the guardian of ',
    provideGuardianPhoneDescription:
      'Please enter the phone number of the guardian of ',
    provideGuardianEmailDescription:
      'Please enter the email address of the guardian of ',
    provideGuardianDOBDescription:
      'Please provide the date of birth of the guardian of ',
    relationToYouDescription: 'What is the relation of nominated beneficiary',
    allocationDescription: 'Define how much of your benefit each nominated beneficiary should receive',
    reviewDescription:
      'Please check the beneficiaries details carefully before confirming',
    // Placeholders
    selectBeneficiaryType: 'Select beneficiary type',
    selectTitle: 'Select Title',
    enterName: 'Enter name',
    selectDate: 'Select date',
    enterPhoneNumber: 'Enter phone number',
    searchAddress: 'Search address',
    confirmAddressPlaceholder: 'Confirm address',
    selectOption: 'Select option',
    selectGuardianTitle: 'Select guardian title',
    enterGuardianName: 'Enter guardian name',
    enterGuardianContact: 'Enter guardian contact',
    enterGuardianEmail: 'Enter guardian email',
    searchGuardianAddress: 'Search guardian address',
    selectRelationship: 'Select relationship',
    enterPercentage: 'Enter percentage (0-100)',
    additionalNotesOptional: 'Additional notes (optional)',
    // Input titles
    savedBeneficiaries: 'Saved Beneficiaries',
    title: 'Title',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    addressSearch: 'Address Search',
    addressConfirmation: 'Address Confirmation',
    guardianRequired: 'Guardian Required',
    guardianFullName: 'Guardian Full Name',
    guardianContactLabel: 'Guardian Contact',
    guardianEmailLabel: 'Guardian Email',
    guardianAddressSearch: 'Guardian Address Search',
    relationship: 'Relationship',
    allocationPercentage: 'Allocation Percentage',
    additionalNotes: 'Additional Notes',
    // Button texts
    select: 'Select',
    skip: 'Skip',
    confirm: 'Confirm',
    done: 'Done',
    // Default props
    addNewBeneficiaryTitle: 'Add New Beneficiary',
    addNewBeneficiaryDescription:
      'Add a new beneficiary to your policy. You can specify their allocation percentage and personal details.',
    // Title options
    titleMr: 'Mr',
    titleMiss: 'Miss',
    titleMrs: 'Mrs',
    titleDoctor: 'Doctor',
    // Relationship options
    relationshipSpouse: 'Spouse',
    relationshipDaughter: 'Daughter',
    relationshipSon: 'Son',
    relationshipOther: 'Other',
    // Form labels
    beneficiaryTitle: "Beneficiary's title",
    selectTheTitle: 'Select the title',
    firstName: 'First name',
    firstNamePlaceholder: 'First name',
    middleName: 'Middle name (optional)',
    middleNamePlaceholder: 'Middle name',
    lastName: 'Last name',
    lastNamePlaceholder: 'Last name',
    beneficiaryEmail: 'Email address',
    beneficiaryEmailPlaceholder: 'example@gmail.com',
    email: 'Email address',
    emailPlaceholder: 'example@gmail.com',
    phoneNumberLabel: 'Phone Number',
    phoneNumberPlaceholder: '',
    // Date of birth labels
    selectDateOfBirth: 'Select date of birth',
    selectGuardianDateOfBirth: 'Select guardian date of birth',
    // Guardian form labels
    guardianFirstName: 'First name',
    guardianFirstNamePlaceholder: 'First name',
    guardianMiddleName: 'Middle name (optional)',
    guardianMiddleNamePlaceholder: 'Middle name',
    guardianLastName: 'Last name',
    guardianLastNamePlaceholder: 'Last name',
    guardianEmailAddress: 'Email address',
    guardianEmailPlaceholder: 'example@gmail.com',
    // Address labels
    addressLine1: 'Address Line 1',
    addressLine1Placeholder: 'Enter address line 1',
    addressLine2: 'Address Line 2',
    addressLine2Placeholder: 'Enter address line 2',
    suburb: 'Suburb',
    suburbPlaceholder: 'Enter suburb',
    state: 'State',
    statePlaceholder: 'Select state',
    postcode: 'Postcode',
    postcodePlaceholder: 'Enter postcode',
    confirmAddressLabel: 'Confirm Address',
    confirmAddressText: 'Please confirm your address',
    // Guardian address labels
    guardianAddressLine1: 'Guardian Address Line 1',
    guardianAddressLine1Placeholder: 'Enter guardian address line 1',
    guardianAddressLine2: 'Guardian Address Line 2',
    guardianAddressLine2Placeholder: 'Enter guardian address line 2',
    guardianSuburb: 'Guardian Suburb',
    guardianSuburbPlaceholder: 'Enter guardian suburb',
    guardianState: 'Guardian State',
    guardianStatePlaceholder: 'Select guardian state',
    guardianPostcode: 'Guardian Postcode',
    guardianPostcodePlaceholder: 'Enter guardian postcode',
    confirmGuardianAddressLabel: 'Confirm Guardian Address',
    confirmGuardianAddressText: 'Please confirm guardian address',
    // Review labels
    reviewInfo: 'INFO',
    reviewName: 'Name:',
    reviewRelation: 'Relation:',
    reviewDateOfBirth: 'Date of birth:',
    reviewContactDetails: 'CONTACT DETAILS',
    reviewTelephone: 'Telephone:',
    reviewEmail: 'Email:',
    reviewAddress: 'Address:',
    reviewGuardianDetails: 'GUARDIAN DETAILS',
    reviewAllocation: 'ALLOCATION',
    dateOfBirthLabel: 'Date of birth: ',
    // Requirements
    requirementsTitle: "To add a beneficiary, please have all the following information available. In the case of a minor beneficiary, you will also require the guardian's details",
    requirementFullName: 'Full Name',
    requirementDateOfBirth: 'Date of Birth',
    requirementFullAddress: 'Full Address',
    requirementContactPhone: 'Contact Phone number',
  },
  switch: {
    AIIDSwitch: 'Additional Investor Information Document(AIID)',
    chooseAFund: 'Choose an investment to switch',
    investments: 'Investments',
    holding: 'Holding',
    switch: 'Switch',
    switchThisFund: 'Switch this fund',
    confirmSwitch: 'Confirm your fund switch',
    confirmSwitchBtn: 'Confirm fund switch',
    descriptionTextSwitch: 'Your switch instruction has been received',
    switchAmountQuestion: 'How much would you like to sell?',
    switchAll: 'Switch all',
    chooseAnInvestmentToSwitchTo: 'Choose an investment to switch to',
    ConfirmYourFundSwitch: 'Confirm your fund switch',
    amountToSwitch: 'Amount to switch: ',
    switchFrom: 'SWITCH FROM',
    switchTo: 'SWITCH TO',
    switchFromFund: 'Switch from',
    switchToFund: 'Switch to',
    switchCompleteMessage: 'Your switch instruction has been received',
    switchNotAllowed: 'Switch not allowed.',
    minInvestment: 'The minimum investment amount is',
    inputInstructions: '',
    switchDisclaimer1: '',
    switchDisclaimer2: '',
  },
  monthlyContribution: {
    totalMonthlyContribution: 'Total monthly contribution',
    collectionDate: 'Collection date',
    viewBankDetails: 'View bank details',
    monthlyAmount: 'Monthly amount',
    addAnotherMonthlyContribution: 'Add another monthly contribution',
    pleaseLoginToTheWeb:
      'Please login to the web app to set up a monthly contribution',
    noBankDetailsFound: 'No bank details found',
  },
  messages: {
    pleaseEnrollBiometricAuthentication:
      'Please enroll a biometric autentication to continue',
    biometricsNotSupported:
      'Biometrics not supported, This device does not support biometric authentication.',
    autenticateMsg: 'Authenticate to continue',
    iConfirmIHaveReadAndAgreeWith: 'I confirm I have read and agree with ',
    iConfirmIHaveReadAndAgreeWithSwitch:
      'I acknowledge I have read and retain a copy of the ',
    transactionCompleteMessage:
      'Transactions should be available to view online and reflected in your account balance on the next business day and will be marked as ‘Pending’ until settlement. The cash balance and remaining allowance details will be updated once the transaction is settled.',
    transactionCompleteMessage2: `• Transactions are processed overnight. Your account balance may take 48 hours to reflect this transaction.
  
• We will send you a contract note for your records.`,
    sellCompleteMessage: 'Your sell instruction has been received',
    switchCompleteMessage: 'Your switch instruction has been received',
    changePaymentSettings:
      'If you would like to make changes to your payment settings, you can do it by logging on to the website.',
    mctfAccountDescription:
      'Please visit the website to take action on your MCTF Account',
    totalAllocationWarning1:
      'You allocated 100% required to save Beneficiary, please confirm by pressing Save Changes, otherwise if you leave this page - all changes will be lost',
    totalAllocationWarning2:
      'You must allocate 100% in order to save the changes to Beneficiaries section, otherwise if you leave this page - all changes will be lost',
  },
  more: {
    myProfile: 'My Profile',
    documents: 'Documents',
    privacyPolicy: 'Privacy policy',
    termsAndConditions: 'Terms & conditions',
    contactUs: 'Contact us',
    legalTextOne:
      'When reporting issues with this application, please quote the following application version number: 3.1.81',
    legalTextTwo:
      'Copyright © 2025 Columbia Threadneedle Investments. Columbia Threadneedle Investments is the global brand name of the Columbia and Threadneedle group of companies. Financial promotions are issued for marketing and information purposes by Columbia Threadneedle Management Limited, authorised and regulated in the UK by the Financial Conduct Authority.',
  },
  address: {
    addressLine1: 'Janus Henderson Investors',
    addressLine2: 'PO Box 9023',
    town: 'Chelmsford',
    city: 'Essex',
    postcode: 'CM99 2WB',
  },
};

// export const Currency1: Record<string, string> = {
//   GBP: 'p',
//   USD: 'c',
//   DEFAULT: 'p',
// };
